table 'Localized Labels'
	isHidden
	lineageTag: e85318d1-d76f-4118-8c46-39e2faf5ad22

	measure 'My Report Title' = 0
		isHidden
		lineageTag: 59340fd6-676d-409f-8079-8bf870e8a7b4

	measure 'My Button Caption' = 0
		isHidden
		lineageTag: eab7bf19-b053-461b-a644-7089dbd998db

	measure 'My Visual Title' = 0
		isHidden
		lineageTag: 74fe64a5-b100-41b4-968c-244298dd96d8

	column unused
		isHidden
		displayFolder: unused
		lineageTag: 613ea557-e9ba-43ad-82b5-fe5dcaf526e7
		summarizeBy: none
		isNameInferred
		sourceColumn: [unused]

		annotation SummarizationSetBy = Automatic

	partition Partition = calculated
		mode: import
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

