table 'Translated Localized Labels'
	lineageTag: 2d6c2162-88cc-4ff8-87af-7785251c89fc

	measure 'My Report Title Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Report Title",
			   "es-ES", "My Report Title",
			   "My Report Title"
			)
		lineageTag: 00b141e5-c42e-442e-955a-b47ad394de4a

	measure 'My Button Caption Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Button Caption",
			   "es-ES", "My Button Caption",
			   "My Button Caption"
			)
		lineageTag: 0d7188d3-e5dd-43ef-8761-632f5ab84d95

	measure 'My Visual Title Label' =
			SWITCH(USERCULTURE(),
			   "en-US", "My Visual Title",
			   "es-ES", "My Visual Title",
			   "My Visual Title"
			)
		lineageTag: a5f02d49-4908-4aac-b24b-ca4c00b3c7ef

	column unused
		isHidden
		displayFolder: unused
		lineageTag: 1802d417-9f12-431b-a7e5-3aef6da7f099
		summarizeBy: none
		isNameInferred
		sourceColumn: [unused]

		annotation SummarizationSetBy = Automatic

	partition Partition = calculated
		mode: import
		source = DATATABLE("unused", STRING, {{"This is a table automatically generated by Translations Builder"}})

